### ISSUE TITLE
Allowing to activate a link directly when it gets a search hit

### ISSUE THREAD

**Issue by lynnard** [fanglingsu/vimb#131]
Back in the day of vimperator there was one feature I used from day to day. I will search for  some string on the page, hit `n` or `N` to get reach the link I want, and hit `<Enter>` to activate it directly. With vimb I have to hit `f` and type the number for the link. It's no big deal but it would be nice if we can add this feature.

**Comment by antoyo** [comment]
We can have this feature with the following mapping:
```
nmap <CR> :eval! window.getSelection().anchorNode.parentNode.click()<CR>
```

**Comment by fanglingsu** [comment]
@antoyo Thank you for this hint. I'll try to implement this in vimb so that the `<CR>` does only do the click when a search is currently active.

**Comment by antoyo** [comment]
Cool.
If it is implemented in `vimb`, there is also a way to allow opening in a new tab with `Ctrl+Enter` (I don't think it is possible with only JavaScript).

**Comment by fanglingsu** [comment]
I've pushed a first attempt to get this working. But vimb does not have control about the link target. tat means if the link or otherwise JavaScript crafted element want to open into new window a new window will be opened. I assume we have to reuse some of the hinting JavaScript to let vimb control where to open the element.

**Comment by fanglingsu** [comment]
This is already implemented.
