### ISSUE TITLE
Cannot unmap default keybinds?

### ISSUE THREAD

**Issue by sdothum** [fanglingsu/vimb#166]
It does not appear that you can unmap the default keybinds.

For nmap "letter" keybinds, I can map Esc to effectively undo the default keybind.

For nmap "Ctrl-letter" keybinds like Ctrl-Q, it doesn't appear you can remap them at all (unless the lhs syntax differs from vim for multikey mappings).

The Ctrl-Q attempt was an experiment. Unmapping regular nmap keys with Esc to play with some normalization between browsers appears sufficiently doable.. Not a big deal but I am curious what restrictions there are to keymaps.

**Comment by fanglingsu** [comment]
The remapping should work. I think you use the wrong syntax as you mentioned vim and vimb are slightly different here. Vimb is more restrictive about how the `{lhs}` should look like, vim allows multiple syntaxes and does mostly not concern about the character case.

Following works for me:

    :nmap <C-Q> <Esc>

May be it would be better to be not as strict on parsing the mappings, but as I wrote the code for that I wanted to get it work, and the stricter way was definitely the faster to implement. And I still like this approach, because it keeps vimb small and hopefully lightweight.

**Comment by sdothum** [comment]
Yes.. it would appear that upper case Q needs to be used in the {Ctrl - lhs}.

**Comment by fanglingsu** [comment]
OK, nice to hear that it works for you too.
