### ISSUE TITLE
Allow unlimited session undo and go back/forward?

### ISSUE THREAD

**Issue by sdothum** [fanglingsu/vimb#167]
Not a biggie and this probably reflects some of my sloppy browsing habits which maybe vimb needs to correct!

Other browsers that natively support tabs allow undoing more than one page (tab) and remember the go back/forward history for that restored page (tab). Not sure how much house keeping bloat that might cause for vimb -- or whether that is even possible at all given its current implementation.

**Comment by fanglingsu** [comment]
The back/forward history is provided by webkit and as I know stored in memory. So each webkit instance and so each vimb instance has it's own history. It would be possible to load the history file into the webkit back/forward history on start, but this has some drawbacks.

1. The start of a new instance would need some more time, depending on the history size.
2. If you use vimb in tabbed environment and browse on some pages in parallel the back/forward history might be bring you to a page you did not expect.
3. Every page you visit is written to back/forward history automatically. If you go one step back in history you create a new record in the history file vimb uses. Any new instance of vimb would have this step back in their history.

As you mentioned this is done by browsers that restore tabs. I can imagine that this would be a nice feature if vimb would have a way to restore tabs or sessions. But at the time there is no such mechanism to do that and may be this could not be done in vimb, because each tab in a own independent running process. The only connection between these processes are done over the files in the `$XDG_CONFIG_HOME/vimb` directory.

I thought about something like `:mksession` but lost my interest for this and found this unneeded as long as vimb does not support tabs natively.

**Comment by sdothum** [comment]
I suspected as much -- that this would be contrary to the lean design of vimb. With better browsing habits, the vimb history search should suffice to visited pages.
