### ISSUE TITLE
Additional events for autocmd

### ISSUE THREAD

**Issue by sdothum** [fanglingsu/vimb#175]
1) add page event to trap attempt to scroll beyond end of page (cursor down, page down). Could be useful for alternate userscripts that "read next page"

2) trap :quit command. If the segfault in #165 isn't fixable, there might be a way to trigger an action to more quickly close that specific page. A total kludge, of course and not ideal..

**Comment by fanglingsu** [comment]
I don't really understand for what this could be useful. You mean that there is dispatched an autocmd everytime the viewed part of the page scrolls or jumps before or beyond some magic borders that are considered to mark beginning or end of a page, right? This will only work on pages that do not load additional data via AJAX that ore inserted in the page so that we loose the meaning of 'page'.

I think the second makes no sense.

**Comment by sdothum** [comment]
I was wondering if there was a way for vimb to trap an attempt to scroll down when the view is already at the bottom of the page (or even when the bottom of the page is displayed -- which might be better). I'm more than likely not understanding how _autopager_ scripts work.. and how to get them to work with the scripts.js file (could be the ones I use with luakit just don't work with vimb).

The second was just a kludge attempt to see if issuing a command would close the segfault related page (relating to the observation that a :quit followed by Esc or even colon to begin a command, immediately closed the window).

**Comment by fanglingsu** [comment]
If you only want to do some things with the reached page end or so in *scripts.js* file, you don't need autocmd. You should be to be notified about current scroll position, the overall length of the site and the dimension of the viewport.
But don't ask me how to do that, I don't know and my JavaScript skills are really poor and the hinting.js is the only useful thing I got working with JavaScript.

If you write a nice script that does something useful, feel free to post it so that I can put it on the [project page][pp].

[pp]: http://fanglingsu.github.io/vimb/scripts.html

**Comment by sdothum** [comment]
Well, my Javascript skills are less than poor.. only good enough to tweak existing scripts on occaision (such as readability scripts). No doubt, having made vimb my primary browser, I will begin to look at a few Javascript extensions I would like to have..

**Comment by fanglingsu** [comment]
OK, i thinks you'll get it working without any changes to vimb.
