### ISSUE TITLE
Few questions from noob

### ISSUE THREAD

**Issue by favetelinguis** [fanglingsu/vimb#213]
Hi I have a few questions im stuck with after trying out vimb tonight.

1: How can i change the search engine used by vimb to google instead of duckduckgo?
2: Are there any web devs tools like a web console in vimb?
3: Are there any examples of using vimb with xmonad groups instead of tabbed?
4: I tried to do some settings in ~/vimb/config but my changes did not get registered by vimb. Is this the correct file for making changes?

I also have a feature request:
Fuzzy search for bookmarks or alternative something as NerdTree.

**Comment by iamleot** [comment]
Hello Henrik!

Henrik Larsson writes:
> Hi I have a few questions im stuck with after trying out vimb tonight.
> 1: How can i change the search engine used by vimb to google instead of duckduckgo?
vimb uses just one simple and plain text configuration file usually
available as ~/.config/vimb/config. In order to do that please just add
in your config the following:

 shortcut-add g=https://www.google.com/search?q=$0
 shortcut-default g

You will see that shortcut-add command is pretty handy, another possible
example:

 shortcut-add wr=http://wordreference.com/$0/$1

In this way you can type as a command something like:

 :open wr enfr example

...and it will open the English -> French translation of "example".

> 2: Are there any web devs tools like a web console in vimb?
There is the WebKit webinspector available if you set the webinspector
option:

 :set webinspector=true

...reload the page and then, "gF" will open the webinspector window.

> 3: Are there any examples of using vimb with xmonad groups instead of tabbed?
Unfortunately I do not know xmonad and I use tabbed or just the native
window manager (in my case dwm) functionalities in order to handle
multiple vimb "tabs".

> 4: I tried to do some settings in ~/vimb/config but my changes did not get registered by vimb. Is this the correct file for making ch
> anges?
The default is ~/.config/vimb/config (or to be exact
$XDG_CONFIG_HOME/vimb/config).

There is also a vimb-users@[0] ML that maybe is more appropriate for
discussion. :)
For further information please also give a look to the vimb(1) man page.


[0]: https://lists.sourceforge.net/lists/listinfo/vimb-users


HTH!
Ciao,
L.

**Comment by fanglingsu** [comment]
All questiona seem to be answered.
