### ISSUE TITLE
Key mapping conflict while in webkit inspector

### ISSUE THREAD

**Issue by jmcantrell** [fanglingsu/vimb#223]
After opening webkit inspector, typing any command that contains an 'o' gets picked up as the mapping to `:open`. The browser should ignore any mappings while the focus is in the inspector.

I'm using the latest version from master.

**Comment by fanglingsu** [comment]
Hm, I strugglet sometimes over this behaviour too, but I've foced myself to switch first to pass-through mode via `CTRL-Z` before using the webinspector.
So I confirm the issue, but I'm not sure how to fix this. I've thought multiple times about how to fix it, but found no good solution.

1.  If we ignore keypresses if the webinspector is focussed we would not be able to close the webinspector by `gF` direct. In fact vimb would not listen to any keypress until the focus is removed by using the mouse. But we want to be able to control vimb by keyboard as far as this is possible.
2. We could add a new browser mode like normal mode or input mode that uses it's own keybindings. This would allow us to ignore all keybindings except of one to close the inspector. But this would also disable the normal mode commands like `:` to start command mode or `r` to reload the page and see what's going on the network.
3. Maybe we could enter pass-through automatic in case the webinspector is opened. But this feels strange to me, because I want to control the browser and don't want to force other people to be switched to pass-through mode that they don't like or need for their work.

I hope you have some nice suggestions how to get rid of the issue, so that we can fix this for all users. Maybe my look to this is to much colored by the internals of vimb instead of the user experience.

**Comment by jmcantrell** [comment]
Thank you for this detailed explanation. I was unaware of pass-through mode, and it's a perfectly acceptable solution, should the following suggestion prove too problematic to implement.

In vim, cycling through the windows can be done with `<c-w><c-w>` (among others, see `:help window-move-cursor`. Provided the `<c-w><whatever>` key combination can be supported in vimb, you could make it so that only the movement keys are enabled when the web inspector is focused. This would allow you to navigate to and from the web inspector without pass-through mode. I can't think of a good way to handle `gF` in the web inspector.

**Comment by fanglingsu** [comment]
The `<c-w>...` is a nice suggestion, but it's not the way I use the webinspector. I like to easily run `:open` command or to reload the page. If we have only the `<c-w>...` you have to switch to the main window with the webview and run you commands. In case I use the pass through mode together with webinspector this is nearly as complicated like with window switching, because to run a command I've to switch back to normal mode by `<c-z>` and run the command. The only benefit of pass through is that the webinspector keeps focused most of the time (depends on the commands).
I don't feel confident with removing normal mode key bindings in case the webinspector is focused at the moment, even if the current behaviour is also not optimal.

**Comment by jmcantrell** [comment]
No worries. Pass-through mode works for me. Thanks again!

**Comment by shioyama** [comment]
Hmm... I've also hit on this and my solution was to bind a key to both open the inspector and go to pass-through mode. But this is at best a hacky solution, and it doesn't really work well - e.g. when I hit the same key combo to close web inspector, I then again go to pass-through mode. Without it though I always forget to go to pass-through and end up accidentally closing the window or doing other things accidentally because I'm not in input mode.

I personally would be fine if vimb ignored anything other than some predefined key (say, escape?) when in the web inspector. To me this is much better than accidentally triggering commands while typing into the console, which can be really annoying (e.g. closing the current page, etc.)

**Comment by fanglingsu** [comment]
@shioyama I'm not sure how to do the webinspector rigtht. I also struggle sometimes with the current behaviour. One way to do it, would be to remove the `gF` keybind to toggle the inspector and use a ex-command like `:inspect` instead that toggles the webinstector. But this would not allow to easily do some nice things like refresch the page by `R` or something similar that I like.
We might think about a special browser mode (a submode of the normal mode) dedicated for the webinspector that allows the user to have special webinspector-mode keybindings. But I didn't spent much time to check what this would mean to the behaviour of vimb in general.

**Comment by shioyama** [comment]
@fanglingsu I thought about this and I think the main issue for me is not the switching to web inspector. It's the fact that there's a console cursor there, which looks like it should trigger input mode but doesn't.

So to me, the ideal behaviour would be: `gF` to open the web inspector, but the console cursor is not blinking at first. *If* you click on the console prompt you get the blinking cursor *and* (like any other input field) you go into input mode. If you click outside of that console or do anything else you go back to normal mode (like you would on a normal page).

I'm not sure this is technically feasible but to me it's the most natural: treat the web inspector like any other webpage.

**Comment by fanglingsu** [comment]
@shioyama Right, `gF` for opening the webinspector is not the case like you mentioned. I've thought about the `gF` to close the webinspector, that might possibly not work if we ignore keypresses when the inspector is focused.
When I understand you right, you want to ignore key bindings in case the webinspector view is focused until the focus is switched by mouse click to the webview or the console. I think this should not be too much work. But I don't like it much to be dependent from the mouse to close the webinspector (click to webview to switch to normal mode and then `gF` to close the inspector). Another issue might be the console, that is potentially not visible to the user `set input-autohide=on` so that there is no point to click to.
But I like the idea to check if the webinspector is focused or not. So we should think of an additional mode that is active as long as the webinspector is focused. This allows the user to define some keybindings that could be triggered from webinspector.

**Comment by fanglingsu** [comment]
Closed because of long time of inactivity.
