### ISSUE TITLE
command :help

### ISSUE THREAD

**Issue by serpent7776** [fanglingsu/vimb#230]
One of great features of vim is \:help command so one can quickly find out what given command or setting do. Vimperator also supports this command, but vimb doesn't.
It would be nice to have documentation built into vimb.

**Comment by fanglingsu** [comment]
I don't see any benefit for this. This would make the install size of the browser much larger because we have to store the documentation somewhere and possible some index to easily find sections of the documentation.
I think vimb is easy and the manual page and the command completion should be enough to use it. I don't think that this would be used if you are familiar with vimb. Because vimb is not as complicated as vim and also has no plugin API and thusands of possible plugins that need to be documented.

**Comment by serpent7776** [comment]
As long as man page is complete I'm ok with this

**Comment by fanglingsu** [comment]
It should be complete, if not, feel free to provide patches to fix it.

**Comment by jeaye** [comment]
@serpent7776 along with the manpage, I've found it useful to just bookmark the vimb manual and open it up as needed. That's not very different from having :help installed by default, considering both are in-browser and you're typically only in your browser if you're on the web (if not, there's always the man page).

**Comment by fanglingsu** [comment]
I don't like to duplicate the help pages by adding some in html. It hard enough to keep the man page nad the vimb page in sync, because I've no script to convert the man page to the github falvoured markdown that is used to generate the vimb help page on github. So I've to do this by hand. And only adding a help page as html would not be what we know from vim. If there would be a `:help` command we should provide also a way to jump to the right section based on a taged search or some fancy document indexing. And this is to much, in my opinion.

**Comment by jeaye** [comment]
On Wed, Aug 12, 2015 at 04:07:28AM -0700, Daniel Carl wrote:
>    I don't like to duplicate the help pages by adding some in html. It hard
>    enough to keep the man page nad the vimb page in sync, because I've no
>    script to convert the man page to the github falvoured markdown that is
>    used to generate the vimb help page on github. So I've to do this by hand.

I've had good luck converting markdown to groff for my own manpages. There are a number of markdown to roff conversion projects on Github and elsewhere; an example usage of the markdown would be available [here](https://github.com/jeaye/sts/blob/master/sts.md) with the conversion done [here](https://github.com/jeaye/sts/blob/master/Makefile#L49).

Might save you some trouble.

**Comment by serpent7776** [comment]
@jeaye thats a good point about vimb manual, thanks
