### ISSUE TITLE
YouTube Video Won't Play

### ISSUE THREAD

**Issue by CaptainKraft** [fanglingsu/vimb#240]
I don't have flash installed and I have plugins=false to prevent any flash silliness otherwise.

I have tested on my laptop and my desktop. Neither play YouTube videos.

I'm on Arch Linux 64bit.

**Comment by sdothum** [comment]
Have you tried enabling html5 for youtube from..

https://www.youtube.com/html5

**Comment by CaptainKraft** [comment]
It is enabled. Videos play just fine in Chromium via HTML5

**Comment by iamleot** [comment]
Hello Jeremiah,

Jeremiah writes:
> I don't have flash installed and I have plugins=false to prevent any
> flash silliness otherwise.
AFAIK gstreamer (the library used by WebKit GTK to handle multimedia
contents) isn't considered a "plugin" and so you can see HTML5 medias
using plugins=false without any problem. Just as a side note: at the
same time some nasty sites (youtube included) need javascript
(scripts=true) to play videos.

> I have tested on my laptop and my desktop. Neither play YouTube
> videos.
> 
> I'm on Arch Linux 64bit.
I think that probably you need more gstreamer plugins in order to properly
watch video directly inside vimb. Here I am running NetBSD and using
pkgsrc and with the following packages I do not have any problem:

 gst-libav-1.4.5nb2
 gst-plugins1-vpx-1.4.5nb1
 gst-plugins1-base-1.4.5nb1
 gst-plugins1-vorbis-1.4.5
 gst-plugins1-ugly-1.4.5
 gst-plugins1-x264-1.4.5
 gst-plugins1-theora-1.4.5
 gst-plugins1-good-1.4.5
 gst-plugins1-oss-1.4.5
 gst-plugins1-ogg-1.4.5

Hopefully they will give an idea regarding other - maybe - not installed
gst-plugins-*.


HTH!
Ciao,
L.

**Comment by CaptainKraft** [comment]
iamleot, you are the man. The gst libs did the trick. Thank you

**Comment by AdrienLemaire** [comment]
fyi: we still need these extra dependencies to watch youtube videos today
Might be good to mention it in the faq.
```
$ pacman -S gst-libav gst-plugins
```
