### ISSUE TITLE
Environment Variables Not Set

### ISSUE THREAD

**Issue by CaptainKraft** [fanglingsu/vimb#241]
The manual says that Vimb sets environment variables such as VIMB_URI. This does not happen for me in Arch Linux x64

**Side note:** I'm trying to setup a way to download and launch youtube videos outside of the browser. My first intuition was using ':sh! youtube-dl -f webm $VIMB_URI' but there are no env variables being set at all by Vimb.

If you know of a better way, that would be very helpful.

edit: spelling

**Comment by sdothum** [comment]
Not sure if this is the best way.. but I configured vimb with..

augroup mygroup
  autocmd LoadCommited https://www.youtube.com/watch* :shell mpv %<CR>
augroup end

If memory serves me right, mpv uses youtube-dl.

**Comment by CaptainKraft** [comment]
That works great for playing videos. Do you know where the file is stored?

**Comment by sdothum** [comment]
Sorry.. have only used this for playback so have never looked for a downloaded file. I don't even see traces of a cache file so might it be streamed directly into mpv?

**Comment by iamleot** [comment]
Hello sdothum and Jeremiah,

sdothum writes:
> Sorry.. have only used this for playback so have never looked for a downloaded file. I don't even see traces of a cache file so might
>  it be streamed directly into mpv?
Yes, usually youtube-dl returns an URL that is playable by mpv (and this
is all done by mpv itself directly using youtube-dl). I think that by
default mpv uses the memory as a cache. It seems that there is also a
--cache-file option but I have never used it.

Usually I have a keybinding (C-M) in order to invoke mpv and play the
video as follow (in the vimb config file... Jeremiah, please note the
"_" and not the "-"! :)):

    nmap <C-M> :sh! mpv "${VIMB_URI}"<CR>

...if I need to download the video (happens more rarely) I just use
something like that. First I yank the URI in vimb via "y" or other
hinting commands, then:

    $ youtube-dl "$(xclip -o)"

...for various video file formats you can also download it like above
and at the same time play it (sometimes mpv's --cache=no can help in
those situation).


Ciao,
L.

**Comment by CaptainKraft** [comment]
I mistyped that into the issue, but I was using the underscore. I also checked env and there are no vimb variables at all.

**Comment by iamleot** [comment]
Hello Jeremiah,

Jeremiah writes:
> I mistyped that into the issue, but I was using the underscore. I also checked env and there are no vimb variables at all.
Can you paste the output from ":shellcmd env", please? I am using
vimb-2.10 and I can see:

    [...]
    VIMB_PID=4200
    VIMB_XID=12582915
    VIMB_URI=http://fanglingsu.github.io/vimb/
    VIMB_SOCKET=/home/leot/.cache/vimb/socket/4200
    VIMB_TITLE=Vimb - The Vim like Browser


Ciao,
L.

**Comment by CaptainKraft** [comment]
Haha, I feel dumb now. I was using VIM_URI
