### ISSUE TITLE
How to create a new hint class ?

### ISSUE THREAD

**Issue by orang-outan** [fanglingsu/vimb#251]
On some websites (Youtube, ... ), the hint engine misses some buttons. 
How to add these classes of elements in the hintable element class ?
It is C configured or script configured ? and how to add it ? 

Thanks

**Comment by fanglingsu** [comment]
The Logic what is hintable according to the selected hintmode is don in the _src/hints.js_ file. I don't know which button do not work, but normally it would be enought to adapt the xpath rules to match the buttons too. These rules are located in the [xpathmap](https://github.com/fanglingsu/vimb/blob/4d9c39b6294933a973b06c20be757a3262ad7710/src/hints.js#L543) map. On the left sinde of the map are the chars identifying the hintmode like 'otY' for `;o`, `;t` and `;Y`.
If you can't get the hints working with this, you might check the [isVisible()](https://github.com/fanglingsu/vimb/blob/4d9c39b6294933a973b06c20be757a3262ad7710/src/hints.js#L87) function, maybe the buttons are considered in some way out of the viewport or otherwise hidden or invisible.

**Comment by orang-outan** [comment]
Thanks for your answer,
The missed item is a <div> and it is from the Youtube comment section.
There is a way to add it through a plugin rather than a source modification. I think it could be great to have a hint script for each website (otherwise no one that uses vimb could read without mouse the comments of Youtube, or a website with some magic js buttons.).

**Comment by fanglingsu** [comment]
A hintscript for each website might be to much for vimb. I'd prefer to fix the hinting in general. I don't have a youtube account and cant see the html so I don't know if the issue is a bug or busshit of youtube. Normally a div is no element that should be hintable, except if it contains some onlclick attribute or some html stuff that marks it for be in someway active.
If you post the div element's attributes I'll see if we can support this natively in vimb. If not you can still got the dirty way and use the user script in _$XDG_CONFIG_HOME/vmb/scripts.js_ and modify the div element if the dom is loaded and the base url is youtube so that it would be processd by the hinting script. I've never done this, but in my opinion this could be a way to do it without any changes in vimb.

**Comment by orang-outan** [comment]
With pentadactyl it is possible to modify dynamically the hint classes.
I think that the dirty way is better than the source modification since it is only a patch for one website ( it is the Load comments at the bottom of Youtube videos).
Actually, the div is loaded by a js script, so it is not created at the startup of the webpage. 
I think that it is maybe better to use pentadactyl for this kind of stuff ( use a light browser for video playing is a little bit stupid). I close the issue cause I found  t
Thanks you for you assistance.
