### ISSUE TITLE
Correct way to close window?

### ISSUE THREAD

**Issue by scobiehague** [fanglingsu/vimb#260]
I'm running vimb-gtk2-2.9 (untabbed) on FreeBSD. I've found vimb the slickests out of the webkit based browsers, but the delay on closing a window using Ctrl-Q bothers me. It takes over 5 seconds. For now I'm using this instead:

```
nmap xx :sh wmctrl -ic $VIMB_XID<CR>
```

This acts the same as clicking the close button in the titlebar of the window, and is near instantaneous. Is there a reason not to use this over :quit, other than checking for running downloads? Perhaps it doesn't close gracefully?

Alternatively, I could Ctrl-Q + Alt-Tab away from a window and leave it to close in the background, while I carry on reading another window. But if I go that route, I at least want some visual feedback that I hit the right keys to close the window e.g.,

```
nmap xx :sh echo Window closing<CR>:quit<CR>
```

The problem with chaining a message to quit is that the console output does not display in vimb. The case is the same for evaluating javascript messages with :e. Is there a way around this? I suspect I could run vimb socketed and send it both a message and a quit command with $VIMB_SOCKET, but then the solution might end up complex. 

Thanks for reading.

**Comment by fanglingsu** [comment]
For the first I thought that the long close time might be related to #165. I've added some debug code and installed `wmctrl` and checked what happens on close. The window close triggers `destroy_window_cb`, `vb_quit` and `vb_clean`, and `<Ctrl-Q>` triggers `vb_quit` and `vb_clean`. So there is nothing wrong on using the `wmctrl` to close the window.
But I can't imagine what should made a difference in the time to close the window in the both cases. Maybe the window closing feels only faster because the window is wiped away from screen during vimb writes the last used page to file and clean up memory gracefully.
I'm interested to find out what takes so long to quot vimb, because the are others affected by this too.

1. Could you write a `return;` into the first line of function `vb_cleanup` in _src/main.c_ so that the memory isn't freed on quit (and the history file is not shriked to it's maximum size by removing duplicate entries).
2. How many lines contains you history file, maybe this takes long to read, cleanup and write (would be skipped by 1.).

According to `nmap xx :sh echo Window closing<CR>:quit<CR>`. You're right, the message can't be seen because it's immediately overwritten by the `:`. It's only a dirty feedback, but you could change something else on the user interface as feedback like this `:nmap xx :set input-bg-normal=#ff00ff<CR>:quit<CR>`

**Comment by fanglingsu** [comment]
@scobiehague Sorry for this off topic question. Do you use the current master and does this compile on FreeBDS? We got and issue (#76) with FreeBSD and changes something on the file locking to fix compile errors, but these changes where revered at 21.10.2015 because of an other issue #235.

**Comment by scobiehague** [comment]
I don't use the version from git, but a FreeBSD pre-built binary reported as version 2.9. My history file is 1554 lines, but even with a blank history file in ~/.config/vimb/history, the delay remains.

If you need me to test further, I can compile the [ports]( http://svnweb.freebsd.org/ports/head/www/vimb-gtk2/) version, which looks from the changelog like it is now at 2.10.

**Comment by scobiehague** [comment]
Is this where I should put the return:

```
static void vb_cleanup(void)
{

    return;
    completion_clean();
    map_cleanup();
...
```

I made a patch to the FreeBSD 2.10 version port with that, but the delay persists.

**Comment by fanglingsu** [comment]
> If you need me to test further, I can compile the ports version, which looks from the changelog like it is now at 2.10.

This version domes not contain the possible broken change. This isn't release at the time. 

```
static void vb_cleanup(void)
{
    return;
    completion_clean();
    map_cleanup();
...
```
Yes that's the rigth place.

The "GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications." sounds not like a reason for the issue. And I think it makes in general no difference.

**Comment by fanglingsu** [comment]
Closed because of long time of inactivity.
