### ISSUE TITLE
Hinting mode and Content Security Policy headers

### ISSUE THREAD

**Issue by plueschopath** [fanglingsu/vimb#266]
Hinting mode doesn't seem to work properly if the webserver enforces certain Content Security Policy headers.

If a webserver (nginx for example) is configured with:

```
add_header Content-Security-Policy "default-src 'self'; upgrade-insecure-requests";
```

hinting doesn't longer work properly. All "numbers" are lined up at the end of the page. Positioning seems to be broken.

Test URL that is enforcing said Content Security Policy: https://partyvan.eu

Is there a way to fix this in vimb or can't we do anything about it?

**Comment by fanglingsu** [comment]
OK, I can reproduce this. This can easily be check also on every other page with `:set auto-response-header=* Content-Security-Policy=default-src 'self';`. The problem is, that the page says that inline style is not allowed, but vimb modifies the DOM to add the hints on the right place. At the moment I've no idea how we can place the hints without using inline style.

**Comment by fanglingsu** [comment]
Maybe this will not happen with webkit2 and the webextension which might provide better access to the dom even on enforced content security.
