### ISSUE TITLE
Can't map to keys that are not handled by vimb internally

### ISSUE THREAD

**Issue by infmagic2047** [fanglingsu/vimb#270]
For example, `:nmap a k` will work, but `:nmap a <Up>` will not. I think when vimb don't handle the key it will let gtk to handle the original, unmapped key, which is `a` but not `<Up>` in this case.

**Comment by fanglingsu** [comment]
I don't understand the issue. Well, `:nmap a k` is clear, if yuo press 'a' you will scroll a little up. What happens with `:nmap a <Up>` for you and what did you expect to happen? The second example does nothing on my system if I press 'a'. As you said, 'a' is translated into `<Up>`, `<Up>` is not handled by vimb so the keyevent of the 'a' bubbles up to the webkit/gtk. But in my case there is no action associated with the a in webkit.
In case I use `:nmap <Down> <Up>` I can see the action in vimb on pressing `<Down>` vimb scrolls down, because the `<Up>` is not known to vimb.

**Comment by yyt16384** [comment]
I would expect `:nmap a <Up>` to make `a` scroll up instead.

In this case I can just use `k`, but there are some keys that don't have an alternative. One example is `<Right>` in command mode.

Another way to fix this would be to handle these keys internally, but there are probably too many keys to handle.

**Comment by fanglingsu** [comment]
> Another way to fix this would be to handle these keys internally, but there are probably too many keys to handle.

That's right, that would be many keys and in case of command mode the keys are are also configurable for gtk. But maybe it would be a good decision to add some keys to vimb to, like the `<Right>` in command mode. This relates to #56 too.

Which keys are missing for the command mode? At the time there are following keys handled by vimb: `<Tab>`, `<S-Tab>`, `<Esc>`, `<C-C>`, `<CR>`, `<Up>`, `<Down>`, `<C-H>`, `<C-W>`, `<C-B>`, `<C-E>`, `<C-U>`, `<C-R>` and all printable ascii chars.

I think to add some cursor movement keys would be enough at the time. Move cursor before the last word, move cursor behind next word, move cursor one char to the right or left.

**Comment by fanglingsu** [comment]
Close because of long time of inactivity.
