### ISSUE TITLE
Hints for elements with click event listener

### ISSUE THREAD

**Issue by kacperzuk** [fanglingsu/vimb#275]
Is is possible to add hints for elements with click event listener added with something like this:

``` js
element.addEventListener("click", function() {});
```

?

It works in VimFx (on the right): http://i.imgur.com/a0E8qhn.png . Generally I see much more hints when using VimFx than when using vimb.

I'll be happy to implement it myself if only someone familiar with vimb and webkit can tell me that's possible and maybe give me a hint or two where to start looking :)

**Comment by fanglingsu** [comment]
It would be great if you could implement this. I think the only file you need to adapt is the [src/hints.js](https://github.com/fanglingsu/vimb/blob/master/src/hints.js). But mayb e it's would not be easy because of the way the hinting is implemented at the time. There are two mechaisms to get the hintable elements, first some XPath rules depending on triggered hint mode and on second place a more fine grained check for the visibility of the elements found by XPath (don't show hints for elements that lay behind another one, or are out of viewport and so on).
I'm not familiar with JavaScript so I don't know how to get the elements that have event listeners assigned. But if this is possible, we should merge the results of the XPath expression with thos elements that have event listeners attached. And than add some logic around line 172 to get the data required for hinting out of the element.

If you have some spare time - maybe you can rework the whole hinting to the way it is done in [vimfx](https://github.com/akhodakivskiy/VimFx/blob/master/extension/lib/hints.coffee). But I'm not sure if vimfx distinguishes between hinting modes like hinting for images or hinting for links. But vimfx does the filtering in opposite order, first get all element within the viewport and remove those that are not visible.

**Comment by lydell** [comment]
FWIW, VimFx uses an internal Firefox API, [nsIEventListenerService](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIEventListenerService), to tell if an element has click event listeners attached to it. There’s no way of knowing using standard DOM (other than monkey-patching `.addEventListener` in all frames).

(Also, VimFx _does_ distinguish between hinting modes, only providing hints for elements that make sense for the current mode.)

(Finally, regarding the order in which elements are filtered: Usually it doesn’t matter for the end result. Benchmark it and choose the fastest order.)

**Comment by fanglingsu** [comment]
There is no good way to do this. I hope there will be a way with webkit2 to do this.
