### ISSUE TITLE
SSL status sometimes does not correctly update on unacceptable TLS certificate

### ISSUE THREAD

**Issue by chairmank** [fanglingsu/vimb#281]
I am reporting an issue in version 2.11.

Steps to reproduce:
1. Load a https page with a valid SSL certificate (e.g. https://duckduckgo.com). The status bar is styled for status `StatusType.VB_STATUS_SSL_VALID`.
2. Load a https page with invalid SSL (e.g. https://expired.badssl.com/).
   1. If `strict-ssl` is on, an "Unable to load page" static page is shown. The status bar is still styled for status `StatusType.VB_STATUS_SSL_VALID` status, and it still shows the old URL "https://duckduckgo.com".
   2. If `strict-ssl` is off, the page is loaded and the status bar is styled for status `StatusType.VB_STATUS_SSL_INVALID`.
3. Navigate back to the first page. Now the status bar shows the URL "https://duckduckgo.com", and it is styled for status `StatusType.VB_STATUS_SSL_INVALID`, even though we know that this site has valid SSL certificate.
4. Reloading http://duckduckgo.com updates the status bar to the expected state.

I think that there a couple of bugs:
- Styling of the status bar does not match the SSL status of the currently shown page.
- When `strict-ssl` is on and a page load fails because of unacceptable TLS certificate, the status bar continues shows the last URL, which is no longer being shown.

In `webview_load_status_cb` in `main.c`, it looks like `set_status` is only called when webkit load status is `WEBKIT_LOAD_COMMITTED`. I hypothesize that there is an opportunity for `vb.state.status_type` to become stale.

**Comment by fanglingsu** [comment]
Thank you for this bug report and for taking the time to dig into the issue. You're right, somethings goes wrong in cases a new url is opened with the status indicator.
But I can't reproduce that the old wrong URL is shown in statusbar. in Case 2.i. I see the "Unable to load page" but the url in the statusbar is "https://expired.badssl.com/". Maybe there are some caching settings that prevent vimb to update the url in statusbar.
There where some issues in the past, where the webkit caching caused some trouble because the load events where not fired.
I'll try to check out what's wrong soon.

**Comment by fanglingsu** [comment]
I've added a check for certificate status also when the page load failes. This should fix case 2.i.
