### ISSUE TITLE
<C-w> in insert mode

### ISSUE THREAD

**Issue by serpent7776** [fanglingsu/vimb#320]
Like in vim `<C-w>` in insert mode should delete word before the cursor. It is very handy.

**Comment by cdlscpmv** [comment]
Try adding this line to `~/.config/gtk-3.0/settings.ini`
````
[Settings] 
key-theme-name=Emacs
````

**Comment by fanglingsu** [comment]
@serpent7776 If you have compiled vimb agains gtk2 you have to set the key theme in the _~/.gtkrc-2.0_ file as
```
gtk-key-theme-name = "Emacs"
```

**Comment by serpent7776** [comment]
Thanks, that do work, but it sets mappings for all gtk apps and this modifies much more that just `<C-w>`. Are these kind of mappings not possible in vimb itself?
Vimperator can handle `<C-w>` in insert mode in default configuration.

**Comment by fanglingsu** [comment]
@serpent7776 I can't find the issue, but there where some discussion about more input mode kebinding capabilities in vimb. It's a hard way to implement thin in vimb, because webkit does not provide any API except from JavaScript to edit text in form fields. And I assume that the attempt to do this would lead to many other issues - if the user tries to enter chinese chars or uses a right to left font direction. Maybe you can do some `imap` keybinding to trigger xdotool to fire a keysequence to force webkit to delete the word (Ctrl-Backspace). Something like `:inoremap <C-W> <Esc>:sh! xdotool key ctrl+backspace<CR>` but this will stop the input mode and I don't have any idea how to reenter it for the right form field.
Another approach could be to add a little funtion to the _~/.config/vimb/scripts.js_ file that starts observers on editable elements and handles the <C-W>.

**Comment by serpent7776** [comment]
@fanglingsu ok, thanks for clarification.
