### ISSUE TITLE
How to get to an alpha release?

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#337]
Hi @fanglingsu,

I wonder what you believe should be done before we could tag a webkit2 alpha release? I am now using the webkit2 branch for some months productively. Yes, not without any pains, that's for sure. But I feel it's definitely worth an alpha release soon.

Even though it might not be completely polished and bug free, I also believe that there is no need to be too shy. You did lots of awesome work on it already. And: it's filling a gap. I do not know about any minimal browser with a current rendering engine (well, I heard about suckless surf patches implementing webkit2). So people might be interested and jump on it. Maybe even help on the dev side. Maybe they just need to be invited and get offered "something"?

What do you think?

**Comment by fanglingsu** [comment]
I'm undecided. I assume many of the vimb user like the hinting, which is not ported yet. But I'm not sure if it's worth to spend so much time on readding this feature. It will be a hard work to implement a working hinting which supports the latest html5 web features.
I personally want to get a working `set header=...` (which does not work properly on startup of vimb, because the first request is fired before we have the chance to submit the header settings via dbus to the extension).

**Comment by hsoft** [comment]
I stopped using vimb a little while ago because Gentoo stopped maintaining old webkit packages, but I'd like to help with the webkit2 effort. To me, type hinting is a deal breaker, so I'd be glad to work on this, but from what I understand, it's a big first step to take for someone like me who's not familiar with the project and webkit.

Still, if nobody's started working on this yet, I'd like to start exploring the issue soon and come back with some sort of WIP PR that would hopefully get early reviews and guidance.

**Comment by fanglingsu** [comment]
@hsoft Thank you for offering your help. You have the permission to start with the hinting, even if it might be a hard work. In my opinion it would be a first step to
- move the hinting.js from master branch into webkit2 branch src/scripts/hinting.js
- call the webextension to inject this into the dom
- add some code to webextension to communicate the the results of the hinting.js like done in src/hints.c of master branch
- add some code to src/ext-proxy that is used to start the hinting and recive data from the webextension

But I have not spend much time to think ybout this.

**Comment by pks-t** [comment]
You do not need the webextension, but could inject the script via WebKitUserContentManager by executing webkit_user_content_manager_add_script. Notifications could then easily be handled by registering a script message handler for this manager and then connecting to the "script-message-received::<NAME>" signal. When executing "window.webkit.messageHandlers.<NAME>.postMessage(<MSG>)", the callback will be executed in the main process.

**Comment by fanglingsu** [comment]
@pks-t I'm note sure if this works, because we have to feed the hinting logic from the main process with new data (typed keys). And I'm not sure if this is secure. In my understanding, these messages can be send/fired by each evil page and not only the hintings.js we inject.
But if this works I'd prefer the script-message way, because it's simple to implement and to maintain.

**Comment by hsoft** [comment]
Thanks for the hint @pks-t, that looks like an interesting and simpler option than going through the webextension.

**Comment by rti** [comment]
That sounds like good news. Great that you want to look into hinting @hsoft. I am missing the feature a lot as well.

I personally thought about distribution package updates for an alpha release as well. What do you think is most important? Arch Linux? Gentoo? BSD?

@fanglingsu Would it be ok if I update the README and transform the TODO list into issues? So we can better spec and track it, form milestones and maybe it's also more easy for people to jump on it?

**Comment by fanglingsu** [comment]
@rti Fell free to update the README and to create issue for the open TODOs.

**Comment by rti** [comment]
@fanglingsu Thanks a lot. Done.

**Comment by fanglingsu** [comment]
@rti Thank you for creating the issues. @rti @hsoft Do you have permission to set yourself as assignee to these issues so that we are informed who works on an issue?

**Comment by rti** [comment]
Nope. I cannot.

**Comment by fanglingsu** [comment]
OK, seem that this is only allowed for contributors that have also push privelege to the repository.

**Comment by fanglingsu** [comment]
But you can make a comment to an issue when you start to work.

**Comment by fanglingsu** [comment]
I'm undecided what to do with the CHANGELOG.md. I don't think it makes sense to add a new section for the webkit2 which contains a lot of lines mentioning that features where removed. May be we should clean out the file and start from zero with the webkit2 features. This refelcts better what we do - starting from scratch. What do you think @rti @hsoft @pks-t?

**Comment by rti** [comment]
Yes. I agree. If it's not called 3.0 final stable people will understand that one feature or the other is still TBD.

**Comment by fanglingsu** [comment]
I've created a new milestone [Version 3.0-alpha](https://github.com/fanglingsu/vimb/milestone/14) containing those tasks and features that I think should be done for a first alpha release. If this is done, we should merge the webkit2 branch into master.

**Comment by pks-t** [comment]
I tend to agree that it does not make sense to have a list of removals in the changelog. A simple mention of the cut would be sufficient. But what _would_ be nice is to have a list of features which are expected not to work with webkit2, so that users will not create new bug reports for known breakages. I think I saw something like this flying around somewhere, though.

**Comment by rti** [comment]
@fanglingsu Woohoo. This is awesome. And we are at 45% solved issues already! Nice!

**Comment by rti** [comment]
I think the creation of the [milestone](https://github.com/fanglingsu/vimb/milestone/14) solves this ticket.
