### ISSUE TITLE
Hinting

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#349]
Allow to highlight clickable elements and assign keyboard shortcuts to them.

Was implemented in vimb2 already. The code should be used as a reference.

There are some insights available:
- https://github.com/fanglingsu/vimb/issues/337#issuecomment-292942461
- https://github.com/fanglingsu/vimb/issues/337#issuecomment-292946599

**Comment by hsoft** [comment]
I've started working on the issue and I have very preliminary work at https://github.com/hsoft/vimb/tree/hints-wip

**Comment by hsoft** [comment]
I've had less time than I hoped for to play with this lately, but I'm almost thankful for that, considering that recent work by @fanglingsu on arbitrary JS execution through the web extension make things much easier. I've rebased at https://github.com/hsoft/vimb/tree/hints . I hope I'll make significant progress soon.

**Comment by hsoft** [comment]
I've tried adding hint styling through `webkit_user_content_manager_add_style_sheet()`, but for reasons beyond my understanding, I couldn't get it to work, so I copy/pasted from the trick used in the `master` branch.

**Comment by fanglingsu** [comment]
@hsoft I think the `webkit_user_content_manager_add_style_sheet` does not work, because added styles are removed in [src/setting.c](https://github.com/fanglingsu/vimb/blob/fe0ace52d36043e93cef91720f41f1ef38f4dd0d/src/setting.c#L639). I thinks we should only remove the user style loaded from the _style.css_ file instead of removing all, but I don't know how we can do that.

But you could add your styles direct in this function after adding or removing the user style. So the styles would be added again after all styles where removed. In Future we can then collect internal used styles, merge and minify them together and insert theme there.

**Comment by hsoft** [comment]
I've made significant progress today by bringing `hints.c` back from the `master` branch (after heavily modifying it of course) and make it compile, not crash, and even barely work.

**Comment by rti** [comment]
@hsoft This is great to hear. Looking forward to test it soon :)

**Comment by hsoft** [comment]
It's mostly working now! I haven't tested all modes and there's still a few edge cases I've commented out, but the basic `f + tag` works as it should.

@fanglingsu I was wondering if you have an idea of what we can do about the `hovering-over-link` signal having disappeared. I'm not too sure what to do about that.

**Comment by fanglingsu** [comment]
@hsoft Do not concern about the hovering. The "hovering-over-link" is now does by "mouse-target-changed", but I'm not sure iw we can emit this by ourself.

**Comment by hsoft** [comment]
Still improving. I've re-enabled the "open in new window" mode, but it's unfortunately limited compared to the old ways due to webkit not letting us set `target` to `_blank` because of the [noopener vulnerability thing](https://mathiasbynens.github.io/rel-noopener/)

**Comment by fanglingsu** [comment]
I've not tested, but you could try to do a middle mouse click to open the target into a new window. But I assume that this does also not work as in webkit1.

**Comment by fanglingsu** [comment]
I've merged the hints branch into webkit2 and we can do the further bug fixing in webkit2 branch.

**Comment by hsoft** [comment]
I've created a [gentoo ebuild for vimb 3.0](https://github.com/hsoft/portage-overlay/commit/10e3e26a1df6800a78e369f04e27dadb5bec096b) so I can start to use it "for real" again and help find bugs, but for reasons I can't figure out yet, hinting doesn't work on vimb "as installed by the system". But strangely, hinting works fine, on the same commit, with `make sandbox`. Investingating...

**Comment by hsoft** [comment]
It turns out it's a problem with my ebuild... [it's fixed now](https://github.com/hsoft/portage-overlay/commit/cc951e2af58987b5d9027fe83377bd86754e9fad)

**Comment by fanglingsu** [comment]
There is a huge bug in the hinting or better in the dbus logic.
1. If I start hinting via `F` or `;t` and fire a link. The link opens into a new window. But at the same time also the previous window where the hinting was started load the new page. So that there are now two windows with the same content openend.
2. If hinting is started again in the first window, the hints are shown in the second window only.
3. If the second window is closed, and hinting is started in the first window. The `;o` appears in the inputbox and the webkit shows a white page and following is printed to cli.

    ** (vimb:8338): WARNING **: Failed dbus method EvalJs: The connection is closed

I think there ist something wrong during the mapping between webextension page id and client in vimb.

**Comment by fanglingsu** [comment]
It turned out that there is another issue. On `;t` we fire the element with `window.open(..., '_blank')` and this causes vimb to not spawn a new instance but to only create a new client within the same ui process, which shares the same settings. We have to find a way to spawn a new vimb instance in case of fired `;t` hint.

**Comment by fanglingsu** [comment]
Are there any known issues of the hinting at the time? Else I'd like to close this issue to work towards the alpha release.

**Comment by hsoft** [comment]
Not that I know of.

**Comment by rti** [comment]
Same here.

**Comment by fanglingsu** [comment]
Hinting does not work in case JavaScript is disabled. I assume that this is related to the changed `fire()` where `window.setTimeout()` is used. This does not work when JavaScript is disabled.

**Comment by rti** [comment]
When opening a link in a new window (normal mode ```F```), the new windows AND the old window load the new page. The old window is expected to stay on the same page though.

**Comment by fanglingsu** [comment]
@rti I thought I'd fixed that by 70b172403a3d97b25f039db658a0b38f495233a2. But you are right, it still does not work. But I think the reason is somewheren in the one ui process but multiple web processed paradigm used in case of window.open() which is generaated by `on_webview_create`.

**Comment by pks-t** [comment]
I'm a bit confused by the hinting code. As far as I see (and the only thing that's currently sensible to do, unfortunately) the code in `hints.c` is mostly a wrapper around `hints.js`. But I cannot see where we acutally use hints.js -- the only site including `hints.js` is `hints.c` via `hints.js.h`, but the defined macro `HINTS_JS` is never used. And in fact, hinting does not work at all on the webkit2 branch for me at 445a420 (adds insight about shortcut-default #365, 2017-05-19).

**Comment by fanglingsu** [comment]
@pks-t The hints.js is minified assigned to JS_HINTS constant and set in _src/setting.c_ in function _user_scripts_. But you are right, the `hints.js.h` was included in the wrong file.
