### ISSUE TITLE
Webkit2 related views

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#359]
Try to use the webkit2 feature of running multiple pages with related view instance ```webkit_web_view_new_with_related_view```

**Comment by fanglingsu** [comment]
We still use the realted webview in case an new window is requested via JavaScript. But we should keep in mind that there might be issues with the settings we apply to the webview. In case of related views the webkit settings are shared and we don't need to set them again. And I think we should signalize the user that there are multiple windows sharing the same settings, even if they where entered only in one window. As this is already part of #360 I close this here.

**Comment by rti** [comment]
Is there any documentation about the concept how vimb uses related views and why it is implemented as it is? I am just curious.

**Comment by fanglingsu** [comment]
Related views are used in case a new window is openend as a popup. In this case it's suggested by the webkit team to use a related view for the popup or the new browser window/tab in our case. I've added the option to open a url into a related view into `vp_load_uri` but this is not used at the time, because there are to many unresolved possible issues.
Normally each window/tab of vimb is a own separated instance of vimb, except of popups which are openen as new window of the same vimb instance like it is done by surf.

**Comment by rti** [comment]
Ok. I understand. Thanks a lot for the clarification.
