### ISSUE TITLE
Zoom via CTRL+ CTRL- (full page zoom)

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#376]
Several vim like tools such as ```zathura``` (PDF viewer) or ```termite``` (Terminal Emulator) support zooming via ```CTRL+``` and ```CTRL-```. In general, this seems to be a common shortcut for zooming in browsers (chromium, firefox, midori). I'd like to have vimb support those shortcuts as well.

**Comment by fanglingsu** [comment]
This is not possible without changing the way like vimb and vim handle key events. Because `CTRL-+` can not be distinguished from `+`. To get this into vimb in general (to allow also to remap such keys like `:nmap <C-+> zi`) we need to rework the key handling completely like mentioned in #247. But this is a huge change.

**Comment by rti** [comment]
Ok, thanks a lot for the explaination. I think for the time being I am perfectly fine with:

```
nmap + zI
nmap - zO
nmap = zz
```
