### ISSUE TITLE
Bitbucket is a mess

### ISSUE THREAD

**Issue by mike402** [fanglingsu/vimb#382]
The layout is completely broken and unusable.
https://bitbucket.org/

vimb 2.12
webkit-gtk2-2.4.11
FreeBSD 11.0-RELEASE-p9
llvm40-4.0.0

**Comment by rti** [comment]
Thanks for the report. This is probably due to the fact that vimb2 uses WebKit 1 which is no longer maintained. 

If you want to use vimb3 with WebKit 2 (the up to date browser engine) you can try the ```webkit2``` branch. It is currently under heavy development, not completely stable nor feature complete, but definitely worth a try. I am using it productively on my arch linux machine. 

And patches are very welcome :)

**Comment by fanglingsu** [comment]
@mike402 As already mentioned, the webkit1 version (master branch or releas 2.12) is no longer supported.
