### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by monstergroup42** [fanglingsu/vimb#418]
Maybe it is only in the 0.3 alpha, but each time I open a new instance of vimb all the settings in the new one are reset to default.

**Comment by fanglingsu** [comment]
@monstergroup42 Settings are read from config file. Settings you change during runtime via `:set var=value` are applied to the running instance/window only. I f you open a new window, a new instance of vimb is started and the config file is written again. You are right, settings changed at runtime do not affect  new instances (with exception of new windows spawned caused by a window.open).
You should set up your setting in the config file. The settings at runtime will never be persisted. This is not a missbehaviour but a design desicion. The behaviour is like in vim.
