### ISSUE TITLE
Firing hint on local anchor link leads to EvalJs timeout

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#421]
### Steps to reproduce

- open this html file with vimb
```
<html><body><a href="#anchor">anchor</a></body></html>
```

- press `f` to enter hints mode
- hit enter to fire the one and only selected hint

### Expected behaviour
- the url changes and ```#anchor``` is appended
- vimb leaves hints mode
- no error is reported

### Actual behaviour
- the url changes and ```#anchor``` is appended
- vimb stays in hints mode (input line still reads `;o`)
- an error is reported `** (vimb:9510): WARNING **: Failed dbus method EvalJs: Timeout was reached
`

**Comment by fanglingsu** [comment]
This error could be fixed by changing `open()` in hints.js to only use `window.setTimeout(function() {e.click();}, 0);` but then hints do never work in case JavaScript is disabled. It seems that it is not allowed or not possible to use timeout functions in case JavaScript is disabled. I don't have any idea of a workaround for this.

**Comment by fanglingsu** [comment]
@rti I started a new branch to get into this issue. I assume that there is a really simple solution to get rid of this by changing the JavaScript execution logic in the webextension. But right now I don't understand why the `e.click()` or the `window.location.href=...` block the webextension or the return from the JavaScript.

**Comment by rti** [comment]
@fanglingsu Thanks a lot. Nice work.
