### ISSUE TITLE
Possible to disable window decorator?

### ISSUE THREAD

**Issue by ionor** [fanglingsu/vimb#439]
Is it possible to turn off the decorators that comes with gtk? i find the titlebar annoying when using a tilling wm?

Thanks

**Comment by fanglingsu** [comment]
I use dwm and don't see any window decorations, so I think you have to set this up for your window manager.

**Comment by fanglingsu** [comment]
@GKFX There is no code in vimb that generates the titlebar. This is generated by the window manager or some other rendering tool. I can't test it, I do not have any window decorator that would generate a titlebar, but https://github.com/PCMan/gtk3-nocsd might help. Another approach would be to change the css for the window decoration like mentioned on https://ogbe.net/blog/gnome_titles.html. But I wonder why you have such titlebars when you have a titling window manager. I think you should remove the compositor or something similar so that no window gets a title bar.

**Comment by GKFX** [comment]
I don't have a tiling window manager, I use a very standard Gnome 3 set-up. However, it does appear that in general if an application doesn't want a titlebar, it should be the thing to remove it, rather than hoping that the window manager will have an option to do it. Due to Wayland's new, more secure model it's become impossible to remove an application's titlebar just by running a script that's not part of the original program. Chucking a bit of CSS into Gnome or removing my compositor will probably do it but is system-wide rather than specific to Vimb. Adding the below code<sup>[[API ref]](https://developer.gimp.org/api/2.0/gtk/GtkWindow.html#gtk-window-set-decorated)</sup> to `create_window` in `main.c` works for me, and is a more correct approach:
````cpp
gtk_window_set_decorated(GTK_WINDOW(window), FALSE);
````
If it were possible for the user to trigger that on a vimb setting that would solve the problem. Ideally it would also be possible to change this setting mid-session, to account for the different requirements of a maximized and reduced-size window, or whatever a user's needs might be.

**Comment by fanglingsu** [comment]
@GKFX Thank you for the hint. But according to the description of this function this might not work when the window is already shown, so the user might not be able to toggle the setting on runtime. Would it help you to make this decision at compile time by setting a flag in src/config.h?

**Comment by GKFX** [comment]
I'm not a great believer in compile-time flags, since they assume that the end-user is compiling the code themselves and happy to recompile for a settings change. Also with the window decorations on a `:set` command it's possible to show the window decorations again if you occasionally want to resize or move the window with the mouse.
