### ISSUE TITLE
Input on htaccess dialog

### ISSUE THREAD

**Issue by dantleech** [fanglingsu/vimb#444]
```
vimb --bug-info
Commit:          3.0-alpha-60-gc346c0c
WebKit compile:  2.16.6
WebKit run:      2.16.6
GTK compile:     3.22.11
GTK run:         3.22.11
libsoup compile: 2.56.0
libsoup run:     2.56.0
Extension dir:   /usr/local/lib/vimb
```

When entering text into the input field vimb is not in INSERT mode, and reserved keys are not captured in the input field.

![image](https://user-images.githubusercontent.com/530801/31481838-bf197bca-af25-11e7-9c96-83b2a97ead38.png)

e.g. above it is impossible to enter the character `o` (without copying and pasting it)

### Steps to reproduce

Open a page protected by htaccess.

### Expected behaviour

Automatically enter INSERT mode for dialogs?

### Actual behaviour

Reserved keys are not captured

**Comment by fanglingsu** [comment]
Thank you for the report.
For testing it would be enough to open a port with netcat like 
```
echo -e "HTTP/1.1 401 Unauthorized\nWWW-Authenticate: Basic realm="Test Authentication"\n\n $(date)" |\
nc -l -p 4000 -q 0
``` 
and open http://localhost:4000 with vimb.

**Comment by dantleech** [comment]
Cool, thanks. Same behavior.

**Comment by fanglingsu** [comment]
@dantleech I've done a littel fix. Vimb will switch now to input mode if a HTTP authentication is requested. But if you press `<Esc>` vimb switches back to normal mode and will not reenter input mode if you put the mouse pointer into the dialog. This is because we do not have any access to the dialog rendered by webkit. If you want to write into the dialog you could manually switch vimb into pass through mode by pressing `<C-Z>`.

**Comment by dantleech** [comment]
Yeah, that works great, thanks :)
