### ISSUE TITLE
headless mode

### ISSUE THREAD

**Issue by Ox16** [fanglingsu/vimb#446]
I need headless mode.
normal use and RECORD all my interaction, passwords etc. and generate a script or file in text mode for using in future in normal headless mode

**Comment by fanglingsu** [comment]
@Ox16 I don't think that this would be possible in the near future. What is you intention to have this headless mode?

**Comment by Ox16** [comment]
I write ;-)
First step: I open normal web browser and normalnavigate (but first run recording all my activiti tothe file)
Second step: Irun by stored file similar web browser.

For example: I open gmail login,read first e-mail and save them.
next i have a script and run
vimb --headlessrun script. and get new emailsimilar my self.

in chrome is headless look this https://developers.google.com/web/updates/2017/04/headless-chrome or other. But here is no record. Only run javascript.

**Comment by fanglingsu** [comment]
This will not work at the time. There are to many dependencies to gtk widget which receive the key-events. If we get the socket-support added to vimb again, the step to run vimb without gui would not be as far away as now. But this would still require gtk toolkit, so it would not be headless.
I think you should use a real headless browser like PhantomJS and learn to use it. A recording isn't as easy as it sounds. Because you have to do things in the application that are normally done by the user (open page and wait if there is enough content before scrolling).
