### ISSUE TITLE
Per site css styles ?

### ISSUE THREAD

**Issue by sigzegv** [fanglingsu/vimb#450]
I find style.css very useful to make custom styles like stylish does in ff or chrome, but I need per site loading. the @document directive doesn't seem to be supported by webkit. Is there a workaround to load per site CSS ?

**Comment by sigzegv** [comment]
He tryied to load custom css file from scripts.js with 
> if (window.location.host === 'twitter.com') { 
>    var cssEl = document.createElement('link'); 
>    cssEl.rel = 'stylesheet'; 
>    cssEl.href = 'file:///home/sigz/.config/vimb/test.css'; 
>    document.body.appendChild(cssEl);
>}

but I get "Not allowed to load local resource: file:///home/sigz/.config/vimb/test.css"

**Comment by fanglingsu** [comment]
@sigzegv Ths JavaScript approach does not work because of the Same Origin Policy. It should be possilbe to inject inline Script into the page instead of the script node which load the JavaScript from file-URI. But at the time ther is no nice way to appy styles depending on the domain. 
I think we could make the file name of the style and the scripts file configurable during runtime so it would be possible to change them usgin auto-commands.

**Comment by sigzegv** [comment]
https://github.com/fanglingsu/vimb/pull/451
