### ISSUE TITLE
Reading mode

### ISSUE THREAD

**Issue by Docbroke** [fanglingsu/vimb#457]
Hi, I have recently switched to vimb as my default browser. This is really a wonderful browser, with plenty of customization possibilities, real boon for a vim user.

One thing I am missing is a reading mode ( something like one present in firefox). This would make reading news articles clutter free. Is there any such thing in plan?

**Comment by josephtoles** [comment]
Firefox reading node seems have a bunch of different features. Looking at the website, it seems the most important feature is a hotkey that changes the fonts and colors to enable easier reading. Vimb doesn't have a mode for this because it's simple to add something lie this into your personal custom Vimb customization.

For example, if what you're looking for is a button that'll let you use different color scheme, then first put the following lines into your `$CONFIG/vimb/config`

```
set stylesheet=off
nm d :set stylesheet=on<CR>
nm v :set stylesheet=off<CR>
```

Then in your `$CONFIG/vimb/style.css` add the following code

```
*,div,pre,textarea,body,input,td,tr,p {
    background-color: #000000 !important;
    background-image: none !important;
    color: #ffffff !important;
    /* font-family: Monospace; */
}
h1,h2,h3,h4 {
    background-color: #000000 !important;
    color: #b8ddea !important;
}
a {
    color: #70e070 !important;
}
a:hover,a:focus {
    color: #7070e0 !important;
}
a:visited {
    color: #e07070 !important;
}
img {
    /* opacity: .5; */
}
img:hover {
    opacity: 1;
}
._hintLabel {
    text-transform: uppercase !important;
    background-color: #e0e070 !important;
    font-size: .9em !important;
    color: #000 !important;
    opacity: 0.4;
}
._hintElem._hintFocus {
    color: #f0f070 !important;
}
._hintElem._hintFocus img {
    opacity: 1;
}
```

Once you have these changes enabled, pressing "d" will make your screen white-on-black and pressing "v" will bring it back to its default colors. You can, of course, configure the CSS to whichever fonts and other stuff you like.

Are there other features of Firefox reader that are important to you?

**Comment by fanglingsu** [comment]
@josephtoles Thank you for answering the question. There is also an option to toggle the behaviour with a singe keybinding `nnoremap d :set stylesheet!<CR><Esc>`

**Comment by Docbroke** [comment]
Thanks for your replies. This is not about only CSS I believe. Reading mode also removes distracting elements. Just look at this images to see the difference.

https://transfer.sh/jfi9a/image_noreading.jpg
https://transfer.sh/t6jIk/image_readingmode.jpg

Customization of fonts, colors etc, are there but removing all other elements makes reading much more easier.

**Comment by josephtoles** [comment]
There isn't such a feature in Vimb at the moment. I expect it's unlikely ever to implement such a feature since Vimb is designed as a minimalist program. However, there's two ways one can go about creating a reading mode. Neither or these are perfect, nor convenient, so I hope you get a better answer.

1. My personal solution is to add some code to my `$CONFIG/vimb/scripts.js` file that removes individual undesirable sections from websites. You can use the line `document.getElementById('id-to-remove').style.display = 'none';` to remove the element with your specified tag. I'm unskilled in JavaScript, so there's probably a better way to do this.

2. The general solution would be to write some more complex logic into your `scripts.js` file that does a more thorough cleanup. It might even be possible to port an [existing](https://github.com/ZachSaucier/Just-Read) library. Please let me know if you figure out how.


@fanglingsu Thanks! I never noticed that before.

**Comment by Docbroke** [comment]
There is ready to use javascript available for various browsers, including webkit based browsers like surf/uzbl. Here is the link https://njw.name/simplyread/
 Though I don't know how if this will work with vimb or how to use it if it works.

**Comment by fanglingsu** [comment]
I'm not sure, but as I remember this simplyread script worked well together with vimb.

**Comment by Docbroke** [comment]
I tried to rename simplyread.js to scripts.js, but it didn't work. If that work to, we need to have some keyboard shortcut for toggle reading mode.

**Comment by Docbroke** [comment]
I did some changes that made reading much easier.

1. Created profile 'news' for news articles
2. changed config to add followings
```    
set cookie-accept=never
set private-browsing=on
set images=off
set font-size=20
set default-zoom=140
set scripts=off
set stylesheet=on
nnoremap d :set stylesheet!<CR><Esc>
```
3. added stylesheet as provided by @josephtoles 
4. now news articles from newsboat (rss reader) are opened with 'vimb -p news '

Is there a way to change profile on the fly ?

**Comment by fanglingsu** [comment]
I think the easiest way for a reading mode would be to download the sources of simplyread, extract the simplyready.js file content to scripts.js. This provides a JS function to toggle the reading mode. So you only need to add some keybinding to run `:e! simplyread();`. E.g. `:nnoremap d :e! simplyread();<CR>`. Cause of the nature the simplyread() function is already toggeling, if the reading mode is already active the next call to this function will disable it.

**Comment by Docbroke** [comment]
Thanks Daniel, that works nice.
One last question, can I toggle two function with single keybinding. as I would like to toggle stylesheet and simplyread together.

**Comment by fanglingsu** [comment]
@Docbroke Yes this should work by chaining the commands together. `:nnoremap <C-S> :set stylesheet!|:e! simplyread();<CR>`

**Comment by Docbroke** [comment]
Thanks, this solves everything for me!
