### ISSUE TITLE
Ctrl+c and Ctrl+v not working

### ISSUE THREAD

**Issue by JJK96** [fanglingsu/vimb#467]
I don't know if this is a bug or just a lack of feature, but I would like to be able to copy and paste text from a webpage, either using vim keybinds (but y is already used) or using these standard shortcuts.

**Comment by fanglingsu** [comment]
@JJK96 I'm not sure if I understand you right. But you can already copy marked text in normal mode by `Y` (uppercase Y). And to paste it in input mode you can use mouse middle click or Ctrl-V+Ctrl-V (first to tell vimb to not interpret the next keystroke as vimb keybinding so that the later is interpreted by gtk or webkit). But you are right, there is no real builtin way to copy test from names register in input mode at the time.

**Comment by JJK96** [comment]
Oh right, I'm sorry, in my version of the man page the line for Y had no explanation yet. 
Solved.
