### ISSUE TITLE
make; src/vimb should just work

### ISSUE THREAD

**Issue by allanwind** [fanglingsu/vimb#515]
Commit:          3.2.0-27-g4f1fce3
WebKit compile:  2.18.6
WebKit run:      2.18.6
GTK compile:     3.22.11
GTK run:         3.22.11
libsoup compile: 2.56.0
libsoup run:     2.56.0
Extension dir:   /usr/local/lib/vimb

### Steps to reproduce
make; src/vimb

### Expected behaviour
vimb should just work.  This is minor issue, for sure, but it would be really nice if vimb would run in your sandbox for ease of development and reinforce the positive first impression (of otherwise smooth sailing given the good README.md).  It might be as simple as changing the default extensions dir to src/webextension. 

### Actual behaviour
** (vimb:20324): ERROR **: Cannot access web extension /usr/local/lib/vimb/webext_main.so
Trace/breakpoint trap

Even less important but the error message should probably explain how the user fixes the problem.

**Comment by allanwind** [comment]
(and yes, I saw sandbox and runsandbox but those are non-standard make targets)

**Comment by fanglingsu** [comment]
@allanwind Yes, the run `runsandbox` is not the default target. But I don't want to change the default tarrget to something only used for developers. This would break existing packages, that use `make && make install`. In my opinion, the inconvenient behaviour is caused by the need to give the variable like `PREFIX` or `DESTDIR` for both steps, `make` and `make install`. This is cause by the lag of an configure script. But I do not like to write such an script only to set two variables.

> Even less important but the error message should probably explain how the user fixes the problem.

If you have ideas how to help the users to get rid of theses "webextension not accessible errors", feel free to provide a pull request for that.

**Comment by allanwind** [comment]
@fanglingsu just to be clear, I was not speaking of the default target (which is "all" as you have it), but of the standard names for targets you expect fo find in a Makefile (see <https://www.gnu.org/software/make/manual/make.html#Goals>).  You expect `make` to build a binary that you can run (in your sandbox), and it is surprising that you have to use a non-standard `make sandbox` for that.

In terms of release management, best practice is to build the software once, test it, then promote it release.  It is not best practice to build one version for testing and another for release, or having to install it just to test it.

I would expect (distribution) packages to install vimb in /usr so they would already be setting PREFIX and/or DESTDIR during build.

Here is another way at looking at it.  `make` should probably not have a dependency on variables used for `make install` (PREFIX/DESTDIR).  Indeed, I was surprised that `make PREFIX=1` was a no-op if preceded by `make`.  Currently you have:

```
PREFIX           ?= /usr/local
BINPREFIX        := $(DESTDIR)$(PREFIX)/bin
RUNPREFIX        := $(PREFIX)
EXTENSIONDIR     := $(RUNPREFIX)/lib/vimb
```

which defaults to:

```
BINPREFIX        := /usr/local//bin
EXTENSIONDIR     := /usr/local/lib/vimb
```

I don't know if (a) the missing DESTDIR on RUNPREFIX or EXTENSIONDIR is intentional, and if (b) RUNPREFIX is indeed expected to be independent of BINPREFIX.  If the answer to (a) and (b) is no,
then extensiondir = basedir(argv[0])/../lib/vimb when installed, and pre-install it would be extensionsdir = basedir(argv[0])/webextension.  If binary is found via PATH you need to walk it too.

I avoid the special case in my projects by building out of source to a build/ directory that mirrors the install tree (hence breaking  the same rule).  This is non-standard too, and justify that by picking up easy to maintain correct `make clean` feature and multi-platform parallel builds.  I understand why you would be hesitant to breaking existing packages for this.

**Comment by fanglingsu** [comment]
@allanwind Thank your reply. You are right. I'm not satisfied how the make works. We need to know the directory where the webextension resides. And this was the workaround to give this to vimb during the make process. It might also be possible to get the path to the webextension during runtime based on the path of the vimb binary. But this looks to mee uncommon to me too. What do you think about this?

The missing `DESTDIR` on `RUNPREFIX` or `EXTENSIONDIR` is intentional. And it might be wrong. This was added to allow to install vimb into user directory (archlinux makepkg). So the extensiondir must be the real target when the package is installed and not the directory tree where the files are installed in.

**Comment by allanwind** [comment]
@fanglingsu sorry, not sure what you are asking me.  My observation is simply that the install-time variable probably doesn't belong at build-time, and the evidence is in the cruft needed sandbox targets.

The other obvious run-time solution is to grab the value from the config file.  Then either check that config file into git, or generate it on `make` suitable for sandbox use.  Generate another version when you run `make install` suitable for PREFIX use.  You have the same problem with how to locate the config file, of course, but I think it's a better problem then recompiling the binary.  It is also not entirely unreasonably to punt on given that the -c option already exist.
