### ISSUE TITLE
Wrapper script breaks file rendering

### ISSUE THREAD

**Issue by lifranc** [fanglingsu/vimb#534]
Nix uses wrapper scripts to pass environment variables to executables. 
Starting the executable from an interactive shell or dmenu with the right variables. local html files will render correctly. Using any variation of the wrapper script will show files as plain text.

Here's the wrapper for vimb 3.3:
```sh
#! /nix/store/r47p5pzx52m3n34vdgqpk5rvqgm0m24m-bash-4.4-p23/bin/bash -e
export GIO_EXTRA_MODULES='/nix/store/myaxl6ik5fc3ima19cv45as6zsqx20gs-glib-networking-2.56.0/lib/gio/modules'${GIO_EXTRA_MODULES:+':'}$GIO_EXTRA_MODULES
export XDG_DATA_DIRS='/nix/store/7lrymaxwf3625zg0z8yhvv4nnq15f1wj-gsettings-desktop-schemas-3.28.0/share/gsettings-schemas/gsettings-desktop-schemas-3.28.0:/nix/store/p4b0avnpcvvj6b108zba9j61fgir5b2k-gtk+3-3.22.30/share/gsettings-schemas/gtk+3-3.22.30:/nix/store/7lrymaxwf3625zg0z8yhvv4nnq15f1wj-gsettings-desktop-schemas-3.28.0/share/gsettings-schemas/gsettings-desktop-schemas-3.28.0:/nix/store/p4b0avnpcvvj6b108zba9j61fgir5b2k-gtk+3-3.22.30/share/gsettings-schemas/gtk+3-3.22.30'${XDG_DATA_DIRS:+':'}$XDG_DATA_DIRS
exec -a "$0" "/nix/store/fgdsas0hz52fvkvmq2ifr9vwahhlxbcl-vimb-3.3.0/bin/.vimb-wrapped"  "${extraFlagsArray[@]}" "$@"
```
 
What could possibly account for this behavior?

**Comment by fanglingsu** [comment]
This sounds strange too me. here where some possibly related issues in the past like #319, #264 or #456 on some systems. The only case I can imagin for such iisues is a different mime type guessing depending on the way vimb is called. There whrere systems where `file -bi fileYouWantToSee.html` retunred not `text/html`, so webkit rendered this file as plain text. Maybe you could try to call this file check with and without the wrapper script and check if the output differs.
But I'm not sure if this would be the right test, because I don't know how webkit does the mime-guessing.

**Comment by lifranc** [comment]
The issue is gone now.
