### ISSUE TITLE
The Incontrollable Downloading of Vimb

### ISSUE THREAD

**Issue by Erikrian-Koira** [fanglingsu/vimb#543]
### Information
* Vimb -version=3.3.0
* Webkit -version=4.2.0

*Hello! Dear @fanglingsu*

### Steps to reproduce
When I enter some websites (such as https://download.blender.org/release/Blender2.79/blender-2.79b-windows64.msi) with Vimb, Vimb will start downloading automatically. And I had to quit the tab to stop it downloading (I do not want to download actually. I just want to read the website).
### Expected behaviour
Vimb can be set to a "manual download mode".
Moreover, how can I set "Aria2" as a download plugin of Vimb?
### Actual behaviour
Vimb downloads the file on such website automatically.
#### PS:
*Finally, Vimb is nearly a perfect browser in my opinion.*

**Comment by fanglingsu** [comment]
@Erikrian-Koira Thank you for your suggestions. I'm not sure what should be done in manual download mode. I could think about some confirmation dialog shown in the inputbox (where the interation with vimb takes place) that show some information about the download to be started (mime-type esitmated size or something like that). And the user has do decide if the download is started or not.
There is no support for external downloaders anymore in vimb since migration to webkit2. Because we can't force webkit2 to write all the known cookies into the cookies file. So the downloads with external tools would probably fail, if they are hidden behind some authentication mechanism. Because we have no way to share the session betwenn webkit and some other tools.

**Comment by AloisMahdal** [comment]
Should the fact that downloads can't be pre-authenticated be a blocker, though?  IMO the requirement seems kind of a stretch.  I think it would be perfectly fine to have downloader that just opens the URL; if it's behind authwall it only seems logical to me that external app should need to re-authenticate.

**Comment by fanglingsu** [comment]
@AloisMahdal You are right. The external downloaded should be able to reauthenticate if we can't share the cookies. So I thinks we should readd the external downloaded to allow users to   provide a script that handles the download.

**Comment by fanglingsu** [comment]
@Erikrian-Koira I've ported the old externam-download-command setting into webkit2 version of vimb. Hope this will help you and other users.
I'm not sure which information of vimb are required for such an downloaded so the downloaded get only the uri to download. The refere URI can be accesse vis env variable `$VIMB_URI` and the configured download path via `$VIMB_DOWNLOAD_PATH`.
