### ISSUE TITLE
Feature request: prevent open-in-new-window

### ISSUE THREAD

**Issue by serussell** [fanglingsu/vimb#544]
(sorry; pressed `<Enter>` in the title -- in vimb -- and it submitted the ticket prematurely)

I'd like an option that could be enabled to force links to open in the same window.  On Mozilla, this is the "expert" option `browser.link.open_newwindow.restriction`.  This option would force links (including those triggered by Javascript) to be opened in the **same** window, rather than opening a new one.  Some sites are really bad about opening every link in a new tab (Qwant is one, and a lot of Google areas like account administration overuse this too), and it'd be helpful to be able to disable it.  Also, for those of us who are running in privacy mode, where every window is fresh, it'd prevent us from having to log in for every new window that's popped up when we're browsing around in-account.

I don't know if Webkit supports this, but if it does, it'd be great if it could be exposed through the vimb configuration options.

**Comment by iamleot** [comment]
Hello Sean,
can you please elaborate further?

(just by the Subject: is not clear what the problem is)


Thank you!

**Comment by fanglingsu** [comment]
Hi @iamleot as I understand @serussell want to prevent vimb brom opening a new related instance in case a link is clicked which contains something that enforces to open a new window/tab (`window.open` or `target="_blank"`). If the user explicitely requests a new window (by `;t` hinting, middle mouse click) we should follow this decission and open the target into new window.

I thought that this would be easy, but as I can see we do not have the information about a possible new window request in `on_webview_decide_policy`. The `on_webview_create` which is only called in case a new instance is requested is to late, because we have to return a new webview. And I have not found some related webkit setting to toggle this behaviour.
@serussell I like you idea of having such an option but I don't know how to achieve this.

**Comment by athrungithub** [comment]
surf browser manage ok middle click in `webview_decide_policy`, never open new window/tab

**Comment by fanglingsu** [comment]
@athrungithub Links with `target="_blank"` are also opened into new window with surf.
@serussell Have you any suggestion how to name the new option?

**Comment by serussell** [comment]
@fanglingsu, following the Firefox setting (if we're making up names, having them be similar to other popular implementations seems logical) how about `open-newwindow-restrictions`?  I don't think it's particularly intuitive; `prevent-newwindow` might be better. But if people are searching how to enable this, they'll probably come across the Firefox method and check if that setting exists in `vimb`.

I don't know how hard it would be to still allow **user** initiated new windows to pass through; it'd be great if `;t` still opened a new window even if this setting were enabled.  I only want the decision to open a new window to be *my* decision, not the web site designer's.

Thanks for looking into this.

**Comment by fanglingsu** [comment]
@serussell The `prevent-newwindow` is now available and seem to work for the case i saw.

**Comment by serussell** [comment]
@fanglingsu Get out!  Really? Holy crap, that's amazing! I'll give it a shot tomorrow.

Thanks!

**Comment by serussell** [comment]
Sorry for the delay, but confirmed working as expected.  Awesome work; thanks!
