### ISSUE TITLE
Smooth scrolling not working with j/k and Ctrl+f/b/d/u

### ISSUE THREAD

**Issue by jluttine** [fanglingsu/vimb#560]
### Steps to reproduce

Open some long web page.

Enable smooth scrolling: `:set smooth-scrolling=true`.

Scroll with arrow keys and Page Up/Down. Nice and smooth.

Then scroll with `j`, `k`, `Ctrl+f`, `Ctrl+b`, `Ctrl+d` and `Ctrl+u`.

### Expected behaviour

I expected smooth scrolling with those vim-like key bindings too.

### Actual behaviour

Not scrolling smoothly.

**Comment by fanglingsu** [comment]
@jluttine I'm undecided about this. I don't like smooth scrolling because it take to much time to scroll. I'm not sure if this can be done easily in vimb without reimplementing the big scrolling bloat of webkit again for our commands. At the time there is no API for scrolling in webkit2 that we could use for our scrolling commands. So the scrolling is done by running some parameterized JavaScript snippets via dbus in the webextension vgl. https://wiki.gnome.org/Projects/WebKitGtk/ProgrammingGuide/Cookbook#Scrolling.
