### ISSUE TITLE
Ephemeral mode

### ISSUE THREAD

**Issue by fanglingsu** [fanglingsu/vimb#562]
Allow to run vimb in ephemeral mode to not store sensitive data in filesystem and to not allow websites to store data in the browser. It makes no sense to allow to switch an always running vimb instance into ephemeral mode. So it's enought to give this by command line option at the time `--ephemeral`.

## affected files
Following files under `$XDG_CONFIG_HOME/vimb` should be used read only when
ephemeral mode is on.
- closed
- command
- coonied.db - this file must not be used because we want the cookies to be
  stored in webkit runtime memory only.
- history
- search

Only the `queue` and `bookmark` files should be allowed to be written.

## do write operations in memory
To provide also completions for url, search queries and commands, it would be great to allow to store those data in memory instead of the files and to merge thems into the result like they where read from the files.

## references
[webkit_web_context_new_ephemeral](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebContext.html#webkit-web-context-new-ephemeral)

**Comment by cdlscpmv** [comment]
Good proposal!

Perhaps, creating a few temporary files in /tmp for every ephemeral instance is one way to go. They can be merged on the fly with the rest of the profile data sitting in ~/.config. The problem is that vimb should somehow detect when the last window assosiated with the instance is closed and then remove the temporary files.

Also, I think a new "closed" file should be created for a new ephemeral instance. This would allow reopening a previously closed window but only if that window had been opened in the ephemeral instance.

**Comment by fanglingsu** [comment]
I don't like the idea to write files in ephemeral mode. OK, ite would be easy to do but on multiuser systems they might leak data. And in case vimb crashes they would be left on disc.

**Comment by cdlscpmv** [comment]
The function `shm_open(3)` stores files in memory on Linux (I guess, the same is true for BSDs also) which implies that they will live till the next reboot if left undeleted. They can be swapped out to disk though, but this also applies to the memory used by WebKit itself.

On Linux the temporary files reside in /dev/shm. By setting appropriate permissions on them the problem of data leaks in multiuser systems can be mitigated.

**Comment by fanglingsu** [comment]
I've implemented Ephemeral/Incognito mode and I'l try it out on my daily work.

**Comment by cdlscpmv** [comment]
I've just tested it, and it seems to work. Unfortunately, the browsing history is not preserved when opening a new window with `:tabopen` (I don't know if cookies are). I don't think it's a big deal, since solving the above issues requires either creating new files or having some sort of IPC between the incognito instances.

**Comment by fanglingsu** [comment]
@cdlscpmv Cookies are also not preserved on opening an new window. But I think this is acceptable for a one window browser at the time.

**Comment by fanglingsu** [comment]
I've merge the branch into master.
