### ISSUE TITLE
feature request: reusable output of shell-commands

### ISSUE THREAD

**Issue by herrsimon** [fanglingsu/vimb#591]
Unless I'm not missing something, it is currently not possible to reuse the output of a shell-command as (part of the input) of another command. For example, when doing
``:nmap x :sh echo :open URI<CR>``, pressing x does not actually open URI but instead just echos ``:open URI``. It would be nice to have reusable shell output, for example via a ``:shc`` command.

**Comment by fanglingsu** [comment]
@herrsimon This is not possible at the time. I can imagine that this would be a nice feature for users to provide this extra knob for customization and automation. But I fear that this could introduce a bunch of issues and vulnerabilities because the shell output is directly used by vimb. So if the shell writes some strange char sequences unwanted things could happen here.
In the old webkit1 based vimb we had the option to run vimb with socket support. This allowed to give ex commands to vimb via socket. It's on the roadmap to bring this feature back to vimb #344 which was used e.g. to implement the formfiller.

**Comment by herrsimon** [comment]
Socket support will introduce the same kind of vulnerabilities as there one can also directly pass the shell output to vimb, but of course a socket will solve the same problem (and is more powerful). The idea to have reusable shell output directly in the gui is therefore not a good one and I will close this issue.
