### ISSUE TITLE
:nohlsearch

### ISSUE THREAD

**Issue by SamHH** [fanglingsu/vimb#612]
It'd be great if vimb had a new command like `:noh`/`:nohlsearch` in (n)vim - it hides search highlighting following a search.

**Comment by fanglingsu** [comment]
@SamHH I don't understand what you want to achieve. Disabling search highlighting does not make any sense for a browser, because there is no cursor that could be moved to the current search hit in the document. If you only like to hide the highlight after the search you could press `<Esc>` key which stops the search and hides the highlight.

**Comment by SamHH** [comment]
I suppose I should have figured out that `<Esc>` would work for that... that's all I wanted, thanks. :slightly_smiling_face:
