### ISSUE TITLE
follow hints completely change on input

### ISSUE THREAD

**Issue by zlice** [fanglingsu/vimb#678]
```
Version:         3.6.0
WebKit compile:  2.26.4
WebKit run:      2.32.1
GTK compile:     3.24.13
GTK run:         3.24.29
libsoup compile: 2.66.4
libsoup run:     2.72.0
Extension dir:   /usr/lib/vimb
```

### Steps to reproduce

per https://github.com/fanglingsu/vimb/issues/616#issuecomment-633316196

see below

### Expected behaviour

follows hints/keys stay the same and you can key them out without thinking

### Actual behaviour

Getting a page with multiple hints that get assigned 2 or more characters (like `fsa`) will 'rewrite' hints as you type.

- Go to youtube
- press `f` to follow
- press the `g` in `gg` for a link
- `gg` changes to `sf` and all other links change as well

usually at this point since things change you have to figure out what to press now since continuing may throw you to another place, or no where at all. During that a timeout may occur and send you somewhere else anyway because you didn't press `gsa` fast enough which was no where to be found on the original follow links.

**Comment by fanglingsu** [comment]
@zlice I'm not sure that I understand you right. Do the hintlabels change only if you press any key? Or do they also change without interaction?
It might be possible that the dom is changes in a way that causes vimb to rerender the hints so that they might become some other labels. This is required to scroll with active links, else the last available hint would be fired automatic if you scroll the viewport away from the area where the hints are placed. Maybe vimb thinks the page is scrolled and recalculates the hints.

**Comment by zlice** [comment]
Only on keypress, but each keypress. Sounds like what's happening.

**Comment by tyjak** [comment]
Do you have this setting `set hint-keys-same-length=on` mentionned here #674 ? 
But still with this setting, hints mode with letter is a bit strange for me, I figure out that tapping first letters of the first word of the link change hint and reduce hint choices. Sometimes can't select hint that is just an icon, beacause it's not a word to type...

**Comment by zlice** [comment]
Yes, with that set I get the same results.

**Comment by zlice** [comment]
Using git latest it works better

Still some weirdness with timing but I can probably tweak that.

```
Version:         3.6.0-34-g652f411
WebKit compile:  2.32.3
WebKit run:      2.32.3
GTK compile:     3.24.29
GTK run:         3.24.29
libsoup compile: 2.72.0
libsoup run:     2.72.0
Extension dir:   /usr//lib/vimb
```
